Repository edualgo/interview-corner, pull requests merged in 2021-02, with the labels that each got.

#70 Find Kth smallest element in a row-column sorted matrix.
  Website Corner/Pages/MultiDimArrays/kSmallestMatrix.html
  Website Corner/Pages/MultiDimArrays/multiArray.html
Labels: SWOC, SWoC30, enhancement

#71 Issue #51 fix
  Website Corner/Pages/Array/firstMissingInt.html
Labels: SWOC, SWoC30, enhancement

#72 solution of max data node solution of #issue 63
  Contributor Corner/Ravi kumar/Generic tree/problem statement Max node data.txt
  Contributor Corner/Ravi kumar/Generic tree/solution of max node tree.h
Labels: SWOC, SWoC20, enhancement

#75 Added the Array Question Issue fix #32
  Website Corner/Pages/Array/array.html
  Website Corner/Pages/Array/maxSubarraySum.html
Labels: SWOC, SWoC20, enhancement

#91 Corrected the Last 3 problems of Arrays which were connected by the same link and Added C++ code in Remove duplicates [issue #46]
  Website Corner/Pages/Array/Remove_duplicates.html
  Website Corner/Pages/Array/array.html
Labels: SWOC, SWoC30, enhancement

#88 Added file permutations.cpp for issue #66
  permutations.cpp
Labels: SWOC, SWoC20, enhancement

#86 spiralDisplay
  Contributor Corner/japneetbhatia/spiralDisplay.cpp
Labels: SWOC, SWoC20
