Repository edualgo/interview-corner, pull requests merged in 2021-01, with the labels that each got.

#36 Corrected the writing mistakes.
  Website Corner/Pages/start.html
Labels: SWOC, SWoC10, enhancement

#41 Updated grammatical errors
  Website Corner/Pages/license.html
  Website Corner/Pages/start.html
  Website Corner/index.html
Labels: SWOC, SWoC10, enhancement

#42 Solved #25 : Added c++ code and typos fixed
  Website Corner/Pages/Array/maxAbsoluteDiff.html
Labels: SWOC, SWoC30, enhancement

#48 Deletion without head pointer
  Website Corner/Pages/Linked List/DeleteNodeWithoutHeadPointer.html
  Website Corner/Pages/Linked List/linkedlist.html
Labels: SWOC, SWoC20, enhancement

#53 Added Neumorphism in Contributors Page #21
  Website Corner/assets/css/styles.css
Labels: SWOC, SWoC20, enhancement

#38 Create painters_partition.cpp
  Contributor Corner/vaishnavi/painters_partition.cpp
Labels: SWOC, SWoC30, enhancement

#67 Modified documentation page
  Website Corner/Pages/start.html
  Website Corner/assets/css/styles.css
Labels: SWOC, SWoC20

#65 Issue #18 Fix
  README.md
Labels: SWOC, SWoC20
